### ISSUE TITLE
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20

### ISSUE THREAD

**Issue by navff** [yc-actions/yc-cr-login#10]
Кажется, что у вас версия 1.2.0 использует node20, однако, всё равно такой warning:
```
Node.js 16 actions are deprecated. Please update the following actions to use Node.js 20: actions/checkout@v3, yc-actions/yc-cr-login@v1.2.0. For more information see: https://github.blog/changelog/2023-09-22-github-actions-transitioning-from-node-16-to-node-20/.
```

Кусок yml:
```
steps:
        - uses: actions/checkout@v3
        - name: Login to Yandex Cloud Container Registry
          id: login-cr
          uses: yc-actions/yc-cr-login@v1.2.0
          with:
            yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}
```

Что делаю не так? Можете, пожалуйста, обновить readme?
