### ISSUE TITLE
Add action registry outputs to simplify work with registry

### ISSUE THREAD

**Issue by emcpow2** [yc-actions/yc-cr-login#7]
AWS ECR login action provides registry in output which allows reusing its value in further steps

https://github.com/aws-actions/amazon-ecr-login/blob/main/action.yml

[Reference workflow](https://docs.github.com/en/actions/deployment/deploying-to-your-cloud-provider/deploying-to-amazon-elastic-container-service#creating-the-workflow)

**Comment by nikolaymatrosov** [comment]
It doesn't make sense for Yandex Cloud Container Registry. At least for this action. It is a thin wrapper, simplifying passing static credentials to docker CLI as it described [here](https://cloud.yandex.com/en/docs/container-registry/operations/authentication#sa-json).

This action does not return anything, so there is nothing to return to the output.

**Comment by emcpow2** [comment]
it does make sense

in the snippet below you may see how it simplifies things. We define `CR_REGISTRY` env var based on login output.

Otherwise I would need to mess around with yandex cloud console, then extract registry id.

Also docker image name becomes simply `$CR_REGISTRY:$CR_REPOSITORY` compared to `cr.yandex/$CR_REGISTRY/$CR_REPOSITORY`.

So, this is a demanding nice to have featue.

```yaml
    - name: Login to Yandex Cloud Container Registry
      id: login-cr
      uses: yc-actions/yc-cr-login@v1
      with:
        yc-sa-json-credentials: ${{ secrets.YC_SA_JSON_CREDENTIALS }}

    - name: Build, tag, and push image to Yandex Cloud Container Registry
      env:
        # CR_REGISTRY: crp00000000000000000
        CR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        CR_REPOSITORY: my-cr-repo
        IMAGE_TAG: ${{ github.sha }}
      run: |
        docker build -t $CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG .
        docker push $CR_REGISTRY/$CR_REPOSITORY:$IMAGE_TAG
```
